# Codecov configuration
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    
    patch:
      default:
        target: 70%
        threshold: 10%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  show_carryforward_flags: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/node_modules/**"
  - "**/coverage/**"
  - "jest.config.js"
  - "jest.setup.js"